#!/usr/bin/env python3
"""Turn profiles/<game>.ini into a header of #defines baked into that game's ktfl.asi.

usage: gen_profile.py PROFILE.ini OUT.h
"""
import sys

DEFAULTS = {
    "console": "1", "dedupe": "0", "log": "ktfl_log.txt",
    "mgr_arg": "3", "entry_arg": "7", "pool_off": "0x218", "type_off": "8",
    "index_swap": "0", "dump": "0",
}
STRINGS = ("name", "exe", "game", "build", "sig_mount", "sig_index", "log")


def parse(path):
    kv = dict(DEFAULTS)
    section = None
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line[0] in ";#":
            continue
        if line[0] == "[":
            section = line[1:line.index("]")].strip().lower()
            if section != "settings":
                if "name" in kv:
                    raise SystemExit("one game section per profile")
                kv["name"] = section
            continue
        if "=" not in line:
            continue
        k, v = (s.strip() for s in line.split("=", 1))
        k = k.lower()
        if not k.startswith("sig_") and ";" in v:
            v = v.split(";", 1)[0].strip()
        if k in ("console", "dedupe"):
            v = "1" if v.lower() in ("1", "true", "yes", "on") else "0"
        if k == "index_args":
            v = v.replace(" ", "").lower()
            if v not in ("pool,entry", "entry,pool"):
                raise SystemExit("index_args must be pool,entry or entry,pool")
            k, v = "index_swap", "1" if v == "entry,pool" else "0"
        kv[k] = v
    for req in ("name", "exe", "sig_mount", "sig_index"):
        if not kv.get(req):
            raise SystemExit(f"missing {req}")
    return kv


def main():
    kv = parse(sys.argv[1])
    out = ["// generated by tools/gen_profile.py, do not edit"]
    for k, v in sorted(kv.items()):
        val = '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"' if k in STRINGS else v
        out.append(f"#define P_{k.upper()} {val}")
    open(sys.argv[2], "w", newline="\n").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
